# Network Intrusion Detection System

The notebook proposes the analysis of the data from the standard NSL KDD Dataset and Machine Learning approches for predictions. 
Algorithms tested in Machine Learning are -:

1. Decision tree classifier
2. K Nearest Neighbour
3. Naive Bayes

## Necessary libraries imported

In [56]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import itertools
import seaborn as sns
import pandas_profiling
import statsmodels.formula.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor
from patsy import dmatrices
from sklearn import datasets
from sklearn.feature_selection import RFE
import sklearn.metrics as metrics
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2, f_classif, mutual_info_classif
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import cross_val_score
from sklearn import metrics
import sklearn.tree as dt
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import warnings 
warnings.filterwarnings('ignore')

## Import Training set and Test set

In [5]:
train=pd.read_csv('Train.txt',sep=',')
test=pd.read_csv('Test.txt',sep=',')

In [6]:
train.head()

0  tcp ftp_data   SF  491   0.1  0.2  0.3  0.4  0.5  ...  0.17  0.03  \
0  0  udp    other   SF  146     0    0    0    0    0  ...  0.00  0.60   
1  0  tcp  private   S0    0     0    0    0    0    0  ...  0.10  0.05   
2  0  tcp     http   SF  232  8153    0    0    0    0  ...  1.00  0.00   
3  0  tcp     http   SF  199   420    0    0    0    0  ...  1.00  0.00   
4  0  tcp  private  REJ    0     0    0    0    0    0  ...  0.07  0.07   

   0.17.1  0.00.6  0.00.7  0.00.8  0.05  0.00.9   normal  20  
0    0.88    0.00    0.00    0.00   0.0    0.00   normal  15  
1    0.00    0.00    1.00    1.00   0.0    0.00  neptune  19  
2    0.03    0.04    0.03    0.01   0.0    0.01   normal  21  
3    0.00    0.00    0.00    0.00   0.0    0.00   normal  21  
4    0.00    0.00    0.00    0.00   1.0    1.00  neptune  21  

[5 rows x 43 columns]

## Clean and Explore Data

### Give column names to datasets

In [7]:
columns=["duration","protocol_type","service","flag","src_bytes","dst_bytes","land","wrong_fragment","urgent","hot",
         "num_failed_logins","logged_in","num_compromised","root_shell","su_attempted","num_root","num_file_creations", 
         "num_shells","num_access_files","num_outbound_cmds","is_host_login","is_guest_login","count","srv_count","serror_rate",
         "srv_serror_rate","rerror_rate","srv_rerror_rate","same_srv_rate","diff_srv_rate","srv_diff_host_rate",
         "dst_host_count","dst_host_srv_count","dst_host_same_srv_rate","dst_host_diff_srv_rate","dst_host_same_src_port_rate",
         "dst_host_srv_diff_host_rate","dst_host_serror_rate","dst_host_srv_serror_rate","dst_host_rerror_rate",
         "dst_host_srv_rerror_rate","attack","last_flag"] 

In [8]:
len(columns)

43

In [9]:
train.columns=columns
test.columns=columns

In [10]:
train.head()

duration protocol_type  service flag  src_bytes  dst_bytes  land  \
0         0           udp    other   SF        146          0     0   
1         0           tcp  private   S0          0          0     0   
2         0           tcp     http   SF        232       8153     0   
3         0           tcp     http   SF        199        420     0   
4         0           tcp  private  REJ          0          0     0   

   wrong_fragment  urgent  hot  ...  dst_host_same_srv_rate  \
0               0       0    0  ...                    0.00   
1               0       0    0  ...                    0.10   
2               0       0    0  ...                    1.00   
3               0       0    0  ...                    1.00   
4               0       0    0  ...                    0.07   

   dst_host_diff_srv_rate  dst_host_same_src_port_rate  \
0                    0.60                         0.88   
1                    0.05                         0.00   
2                    0.00                         0.03   
3                    0.00                         0.00   
4                    0.07                         0.00   

   dst_host_srv_diff_host_rate  dst_host_serror_rate  \
0                         0.00                  0.00   
1                         0.00                  1.00   
2                         0.04                  0.03   
3                         0.00                  0.00   
4                         0.00                  0.00   

   dst_host_srv_serror_rate  dst_host_rerror_rate  dst_host_srv_rerror_rate  \
0                      0.00                   0.0                      0.00   
1                      1.00                   0.0                      0.00   
2                      0.01                   0.0                      0.01   
3                      0.00                   0.0                      0.00   
4                      0.00                   1.0                      1.00   

    attack  last_flag  
0   normal         15  
1  neptune         19  
2   normal         21  
3   normal         21  
4  neptune         21  

[5 rows x 43 columns]

In [11]:
train.head()

duration protocol_type  service flag  src_bytes  dst_bytes  land  \
0         0           udp    other   SF        146          0     0   
1         0           tcp  private   S0          0          0     0   
2         0           tcp     http   SF        232       8153     0   
3         0           tcp     http   SF        199        420     0   
4         0           tcp  private  REJ          0          0     0   

   wrong_fragment  urgent  hot  ...  dst_host_same_srv_rate  \
0               0       0    0  ...                    0.00   
1               0       0    0  ...                    0.10   
2               0       0    0  ...                    1.00   
3               0       0    0  ...                    1.00   
4               0       0    0  ...                    0.07   

   dst_host_diff_srv_rate  dst_host_same_src_port_rate  \
0                    0.60                         0.88   
1                    0.05                         0.00   
2                    0.00                         0.03   
3                    0.00                         0.00   
4                    0.07                         0.00   

   dst_host_srv_diff_host_rate  dst_host_serror_rate  \
0                         0.00                  0.00   
1                         0.00                  1.00   
2                         0.04                  0.03   
3                         0.00                  0.00   
4                         0.00                  0.00   

   dst_host_srv_serror_rate  dst_host_rerror_rate  dst_host_srv_rerror_rate  \
0                      0.00                   0.0                      0.00   
1                      1.00                   0.0                      0.00   
2                      0.01                   0.0                      0.01   
3                      0.00                   0.0                      0.00   
4                      0.00                   1.0                      1.00   

    attack  last_flag  
0   normal         15  
1  neptune         19  
2   normal         21  
3   normal         21  
4  neptune         21  

[5 rows x 43 columns]

### Categorize Attacks

- 0 - Normal
- 1 - DoS = back , land , pod , neptune , smurf , teardrop , apache2 , udpstorm , processtable , worm , mailbomb
- 2 - Probe = satan , ipsweep , nmap , portsweep , mscan , saint
- 3 - R2L = guess_passwd , ftp_write , imap , phf , multihop , warezmaster , warezclient , spy , xlock , xsnoop , snmpguess , snmpgetattack , httptunnel , sendmail , named
- 4 - U2R = buffer_overflow , loadmodule , rootkit , perl , sqlattack , xterm , ps

In [12]:
train.loc[train.attack=='normal','attack_class']=0

train.loc[(train.attack=='back') | (train.attack=='land') | (train.attack=='pod') | (train.attack=='neptune') | 
         (train.attack=='smurf') | (train.attack=='teardrop') | (train.attack=='apache2') | (train.attack=='udpstorm') | 
         (train.attack=='processtable') | (train.attack=='worm') | (train.attack=='mailbomb'),'attack_class']=1

train.loc[(train.attack=='satan') | (train.attack=='ipsweep') | (train.attack=='nmap') | (train.attack=='portsweep') | 
          (train.attack=='mscan') | (train.attack=='saint'),'attack_class']=2

train.loc[(train.attack=='guess_passwd') | (train.attack=='ftp_write') | (train.attack=='imap') | (train.attack=='phf') | 
          (train.attack=='multihop') | (train.attack=='warezmaster') | (train.attack=='warezclient') | (train.attack=='spy') | 
          (train.attack=='xlock') | (train.attack=='xsnoop') | (train.attack=='snmpguess') | (train.attack=='snmpgetattack') | 
          (train.attack=='httptunnel') | (train.attack=='sendmail') | (train.attack=='named'),'attack_class']=3

train.loc[(train.attack=='buffer_overflow') | (train.attack=='loadmodule') | (train.attack=='rootkit') | (train.attack=='perl') | 
          (train.attack=='sqlattack') | (train.attack=='xterm') | (train.attack=='ps'),'attack_class']=4

In [13]:
test.loc[test.attack=='normal','attack_class']=0

test.loc[(test.attack=='back') | (test.attack=='land') | (test.attack=='pod') | (test.attack=='neptune') | 
         (test.attack=='smurf') | (test.attack=='teardrop') | (test.attack=='apache2') | (test.attack=='udpstorm') | 
         (test.attack=='processtable') | (test.attack=='worm') | (test.attack=='mailbomb'),'attack_class']=1

test.loc[(test.attack=='satan') | (test.attack=='ipsweep') | (test.attack=='nmap') | (test.attack=='portsweep') | 
          (test.attack=='mscan') | (test.attack=='saint'),'attack_class']=2

test.loc[(test.attack=='guess_passwd') | (test.attack=='ftp_write') | (test.attack=='imap') | (test.attack=='phf') | 
          (test.attack=='multihop') | (test.attack=='warezmaster') | (test.attack=='warezclient') | (test.attack=='spy') | 
          (test.attack=='xlock') | (test.attack=='xsnoop') | (test.attack=='snmpguess') | (test.attack=='snmpgetattack') | 
          (test.attack=='httptunnel') | (test.attack=='sendmail') | (test.attack=='named'),'attack_class']=3

test.loc[(test.attack=='buffer_overflow') | (test.attack=='loadmodule') | (test.attack=='rootkit') | (test.attack=='perl') | 
          (test.attack=='sqlattack') | (test.attack=='xterm') | (test.attack=='ps'),'attack_class']=4

In [14]:
train.head()

duration protocol_type  service flag  src_bytes  dst_bytes  land  \
0         0           udp    other   SF        146          0     0   
1         0           tcp  private   S0          0          0     0   
2         0           tcp     http   SF        232       8153     0   
3         0           tcp     http   SF        199        420     0   
4         0           tcp  private  REJ          0          0     0   

   wrong_fragment  urgent  hot  ...  dst_host_diff_srv_rate  \
0               0       0    0  ...                    0.60   
1               0       0    0  ...                    0.05   
2               0       0    0  ...                    0.00   
3               0       0    0  ...                    0.00   
4               0       0    0  ...                    0.07   

   dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                         0.88                         0.00   
1                         0.00                         0.00   
2                         0.03                         0.04   
3                         0.00                         0.00   
4                         0.00                         0.00   

   dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                  0.00                      0.00                   0.0   
1                  1.00                      1.00                   0.0   
2                  0.03                      0.01                   0.0   
3                  0.00                      0.00                   0.0   
4                  0.00                      0.00                   1.0   

   dst_host_srv_rerror_rate   attack  last_flag  attack_class  
0                      0.00   normal         15           0.0  
1                      0.00  neptune         19           1.0  
2                      0.01   normal         21           0.0  
3                      0.00   normal         21           0.0  
4                      1.00  neptune         21           1.0  

[5 rows x 44 columns]

In [15]:
test.head()

duration protocol_type   service  flag  src_bytes  dst_bytes  land  \
0         0           tcp   private   REJ          0          0     0   
1         2           tcp  ftp_data    SF      12983          0     0   
2         0          icmp     eco_i    SF         20          0     0   
3         1           tcp    telnet  RSTO          0         15     0   
4         0           tcp      http    SF        267      14515     0   

   wrong_fragment  urgent  hot  ...  dst_host_diff_srv_rate  \
0               0       0    0  ...                    0.06   
1               0       0    0  ...                    0.04   
2               0       0    0  ...                    0.00   
3               0       0    0  ...                    0.17   
4               0       0    0  ...                    0.00   

   dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                         0.00                         0.00   
1                         0.61                         0.02   
2                         1.00                         0.28   
3                         0.03                         0.02   
4                         0.01                         0.03   

   dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                  0.00                       0.0                  1.00   
1                  0.00                       0.0                  0.00   
2                  0.00                       0.0                  0.00   
3                  0.00                       0.0                  0.83   
4                  0.01                       0.0                  0.00   

   dst_host_srv_rerror_rate   attack  last_flag  attack_class  
0                      1.00  neptune         21           1.0  
1                      0.00   normal         21           0.0  
2                      0.00    saint         15           2.0  
3                      0.71    mscan         11           2.0  
4                      0.00   normal         21           0.0  

[5 rows x 44 columns]

### Segregate Categorical and Numerical features

In [16]:
numeric_var_names=[key for key in dict(train.dtypes) if dict(train.dtypes)[key] in ['float64', 'int64', 'float32', 'int32']]
cat_var_names=[key for key in dict(train.dtypes) if dict(train.dtypes)[key] in ['object', 'O']]

In [17]:
numeric_var_names

['duration',
 'src_bytes',
 'dst_bytes',
 'land',
 'wrong_fragment',
 'urgent',
 'hot',
 'num_failed_logins',
 'logged_in',
 'num_compromised',
 'root_shell',
 'su_attempted',
 'num_root',
 'num_file_creations',
 'num_shells',
 'num_access_files',
 'num_outbound_cmds',
 'is_host_login',
 'is_guest_login',
 'count',
 'srv_count',
 'serror_rate',
 'srv_serror_rate',
 'rerror_rate',
 'srv_rerror_rate',
 'same_srv_rate',
 'diff_srv_rate',
 'srv_diff_host_rate',
 'dst_host_count',
 'dst_host_srv_count',
 'dst_host_same_srv_rate',
 'dst_host_diff_srv_rate',
 'dst_host_same_src_port_rate',
 'dst_host_srv_diff_host_rate',
 'dst_host_serror_rate',
 'dst_host_srv_serror_rate',
 'dst_host_rerror_rate',
 'dst_host_srv_rerror_rate',
 'last_flag',
 'attack_class']

In [18]:
cat_var_names

['protocol_type', 'service', 'flag', 'attack']

In [19]:
train_num=train[numeric_var_names]
test_num=test[numeric_var_names]
train_num.head()

duration  src_bytes  dst_bytes  land  wrong_fragment  urgent  hot  \
0         0        146          0     0               0       0    0   
1         0          0          0     0               0       0    0   
2         0        232       8153     0               0       0    0   
3         0        199        420     0               0       0    0   
4         0          0          0     0               0       0    0   

   num_failed_logins  logged_in  num_compromised  ...  dst_host_same_srv_rate  \
0                  0          0                0  ...                    0.00   
1                  0          0                0  ...                    0.10   
2                  0          1                0  ...                    1.00   
3                  0          1                0  ...                    1.00   
4                  0          0                0  ...                    0.07   

   dst_host_diff_srv_rate  dst_host_same_src_port_rate  \
0                    0.60                         0.88   
1                    0.05                         0.00   
2                    0.00                         0.03   
3                    0.00                         0.00   
4                    0.07                         0.00   

   dst_host_srv_diff_host_rate  dst_host_serror_rate  \
0                         0.00                  0.00   
1                         0.00                  1.00   
2                         0.04                  0.03   
3                         0.00                  0.00   
4                         0.00                  0.00   

   dst_host_srv_serror_rate  dst_host_rerror_rate  dst_host_srv_rerror_rate  \
0                      0.00                   0.0                      0.00   
1                      1.00                   0.0                      0.00   
2                      0.01                   0.0                      0.01   
3                      0.00                   0.0                      0.00   
4                      0.00                   1.0                      1.00   

   last_flag  attack_class  
0         15           0.0  
1         19           1.0  
2         21           0.0  
3         21           0.0  
4         21           1.0  

[5 rows x 40 columns]

In [20]:
train_cat=train[cat_var_names]
test_cat=test[cat_var_names]
train_cat.head(5)

protocol_type  service flag   attack
0           udp    other   SF   normal
1           tcp  private   S0  neptune
2           tcp     http   SF   normal
3           tcp     http   SF   normal
4           tcp  private  REJ  neptune

### Handling Outliers

In [21]:
#Handling Outliers
def outlier_capping(x):
    x = x.clip(upper=x.quantile(0.99))
    x = x.clip(lower=x.quantile(0.01))
    return x

train_num=train_num.apply(outlier_capping)

### Dummy variable creation

In [22]:
# function to create dummy variable
def create_dummies( df, colname ):
    col_dummies = pd.get_dummies(df[colname], prefix=colname, drop_first=True)
    df = pd.concat([df, col_dummies], axis=1)
    df.drop( colname, axis = 1, inplace = True )
    return(df)

In [23]:
for c_feature in ['protocol_type', 'service', 'flag', 'attack']:
    train_cat = create_dummies(train_cat,c_feature)
    test_cat = create_dummies(test_cat,c_feature)
train_cat.head()

protocol_type_tcp  protocol_type_udp  service_X11  service_Z39_50  \
0                  0                  1            0               0   
1                  1                  0            0               0   
2                  1                  0            0               0   
3                  1                  0            0               0   
4                  1                  0            0               0   

   service_aol  service_auth  service_bgp  service_courier  service_csnet_ns  \
0            0             0            0                0                 0   
1            0             0            0                0                 0   
2            0             0            0                0                 0   
3            0             0            0                0                 0   
4            0             0            0                0                 0   

   service_ctf  ...  attack_phf  attack_pod  attack_portsweep  attack_rootkit  \
0            0  ...           0           0                 0               0   
1            0  ...           0           0                 0               0   
2            0  ...           0           0                 0               0   
3            0  ...           0           0                 0               0   
4            0  ...           0           0                 0               0   

   attack_satan  attack_smurf  attack_spy  attack_teardrop  \
0             0             0           0                0   
1             0             0           0                0   
2             0             0           0                0   
3             0             0           0                0   
4             0             0           0                0   

   attack_warezclient  attack_warezmaster  
0                   0                   0  
1                   0                   0  
2                   0                   0  
3                   0                   0  
4                   0                   0  

[5 rows x 103 columns]

### Join Numerical and Categorical DataFrames

In [24]:
train_new = pd.concat([train_num, train_cat], axis=1)
test_new = pd.concat([test_num, test_cat], axis=1)
train_new.head()

duration  src_bytes  dst_bytes  land  wrong_fragment  urgent  hot  \
0       0.0      146.0        0.0   0.0             0.0     0.0  0.0   
1       0.0        0.0        0.0   0.0             0.0     0.0  0.0   
2       0.0      232.0     8153.0   0.0             0.0     0.0  0.0   
3       0.0      199.0      420.0   0.0             0.0     0.0  0.0   
4       0.0        0.0        0.0   0.0             0.0     0.0  0.0   

   num_failed_logins  logged_in  num_compromised  ...  attack_phf  attack_pod  \
0                0.0          0              0.0  ...           0           0   
1                0.0          0              0.0  ...           0           0   
2                0.0          1              0.0  ...           0           0   
3                0.0          1              0.0  ...           0           0   
4                0.0          0              0.0  ...           0           0   

   attack_portsweep  attack_rootkit  attack_satan  attack_smurf  attack_spy  \
0                 0               0             0             0           0   
1                 0               0             0             0           0   
2                 0               0             0             0           0   
3                 0               0             0             0           0   
4                 0               0             0             0           0   

   attack_teardrop  attack_warezclient  attack_warezmaster  
0                0                   0                   0  
1                0                   0                   0  
2                0                   0                   0  
3                0                   0                   0  
4                0                   0                   0  

[5 rows x 143 columns]

### Drop Columns

In [25]:
# Creating Data audit Report
def var_summary(x):
    return pd.Series([x.var()], index=['VAR'])

num_summary=train_num.apply(lambda x: var_summary(x)).T

In [26]:
num_summary

VAR
duration                     1.200926e+06
src_bytes                    3.767413e+07
dst_bytes                    1.447275e+07
land                         0.000000e+00
wrong_fragment               0.000000e+00
urgent                       0.000000e+00
hot                          1.237833e-01
num_failed_logins            0.000000e+00
logged_in                    2.391315e-01
num_compromised              1.010448e-02
root_shell                   0.000000e+00
su_attempted                 0.000000e+00
num_root                     0.000000e+00
num_file_creations           0.000000e+00
num_shells                   0.000000e+00
num_access_files             0.000000e+00
num_outbound_cmds            0.000000e+00
is_host_login                0.000000e+00
is_guest_login               0.000000e+00
count                        1.311225e+04
srv_count                    5.100879e+03
serror_rate                  1.993236e-01
srv_serror_rate              1.998301e-01
rerror_rate                  1.026796e-01
srv_rerror_rate              1.047482e-01
same_srv_rate                1.932689e-01
diff_srv_rate                3.251351e-02
srv_diff_host_rate           6.751235e-02
dst_host_count               9.841934e+03
dst_host_srv_count           1.225512e+04
dst_host_same_srv_rate       2.015562e-01
dst_host_diff_srv_rate       3.569171e-02
dst_host_same_src_port_rate  9.547998e-02
dst_host_srv_diff_host_rate  8.535578e-03
dst_host_serror_rate         1.978338e-01
dst_host_srv_serror_rate     1.986219e-01
dst_host_rerror_rate         9.397818e-02
dst_host_srv_rerror_rate     1.020550e-01
last_flag                    4.249381e+00
attack_class                 4.472928e-01

In [28]:
corrm=train_new.corr()
corrm

duration  src_bytes  dst_bytes  land  wrong_fragment  \
duration            1.000000   0.011740   0.036892   NaN             NaN   
src_bytes           0.011740   1.000000   0.127827   NaN             NaN   
dst_bytes           0.036892   0.127827   1.000000   NaN             NaN   
land                     NaN        NaN        NaN   NaN             NaN   
wrong_fragment           NaN        NaN        NaN   NaN             NaN   
...                      ...        ...        ...   ...             ...   
attack_smurf       -0.020279  -0.002928  -0.051676   NaN             NaN   
attack_spy          0.000605  -0.000555  -0.000156   NaN             NaN   
attack_teardrop    -0.011691  -0.013779  -0.029791   NaN             NaN   
attack_warezclient  0.037013   0.047995  -0.011541   NaN             NaN   
attack_warezmaster -0.001571  -0.002012   0.064962   NaN             NaN   

                    urgent       hot  num_failed_logins  logged_in  \
duration               NaN  0.021274                NaN  -0.064538   
src_bytes              NaN  0.379973                NaN   0.163275   
dst_bytes              NaN  0.127002                NaN   0.421999   
land                   NaN       NaN                NaN        NaN   
wrong_fragment         NaN       NaN                NaN        NaN   
...                    ...       ...                ...        ...   
attack_smurf           NaN -0.020616                NaN  -0.118539   
attack_spy             NaN -0.000561                NaN   0.000850   
attack_teardrop        NaN -0.011886                NaN  -0.068341   
attack_warezclient     NaN  0.270177                NaN   0.104233   
attack_warezmaster     NaN  0.003599                NaN  -0.007621   

                    num_compromised  ...  attack_phf  attack_pod  \
duration                   0.062081  ...   -0.000757   -0.005534   
src_bytes                  0.603363  ...   -0.000898    0.002845   
dst_bytes                  0.237363  ...    0.010050   -0.014104   
land                            NaN  ...         NaN         NaN   
wrong_fragment                  NaN  ...         NaN         NaN   
...                             ...  ...         ...         ...   
attack_smurf              -0.014876  ...   -0.000825   -0.005856   
attack_spy                -0.000405  ...   -0.000022   -0.000159   
attack_teardrop           -0.008576  ...   -0.000476   -0.003376   
attack_warezclient        -0.008567  ...   -0.000475   -0.003372   
attack_warezmaster        -0.001280  ...   -0.000071   -0.000504   

                    attack_portsweep  attack_rootkit  attack_satan  \
duration                    0.408874       -0.000414     -0.023837   
src_bytes                  -0.022114       -0.001067     -0.028784   
dst_bytes                  -0.053377        0.006873     -0.060374   
land                             NaN             NaN           NaN   
wrong_fragment                   NaN             NaN           NaN   
...                              ...             ...           ...   
attack_smurf               -0.022607       -0.001305     -0.025242   
attack_spy                 -0.000615       -0.000036     -0.000687   
attack_teardrop            -0.013034       -0.000752     -0.014553   
attack_warezclient         -0.013019       -0.000752     -0.014536   
attack_warezmaster         -0.001945       -0.000112     -0.002172   

                    attack_smurf  attack_spy  attack_teardrop  \
duration               -0.020279    0.000605        -0.011691   
src_bytes              -0.002928   -0.000555        -0.013779   
dst_bytes              -0.051676   -0.000156        -0.029791   
land                         NaN         NaN              NaN   
wrong_fragment               NaN         NaN              NaN   
...                          ...         ...              ...   
attack_smurf            1.000000   -0.000584        -0.012370   
attack_spy             -0.000584    1.000000        -0.000336   
attack_teardrop        

Columns are dropped on following basis -: 
1. Based on low variance (near zero variance)
2. High correlations between two numerical variables

Following columns are decided to be dropped -:
land , wrong_fragment , urgent , num_failed_logins , root_shell , su_attempted , num_root , num_file_creations , num_shells , num_access_files , num_outbound_cmds , is_host_login , is_guest_login , dst_host_rerror_rate , dst_host_serror_rate , dst_host_srv_rerror_rate , dst_host_srv_serror_rate , num_root,num_outbound_cmds , srv_rerror_rate , srv_serror_rate

In [29]:
train_new.drop(columns=['land','wrong_fragment','urgent','num_failed_logins',"root_shell","su_attempted","num_root",
                        "num_file_creations","num_shells","num_access_files","num_outbound_cmds","is_host_login","is_guest_login",
                        'dst_host_rerror_rate','dst_host_serror_rate','dst_host_srv_rerror_rate','dst_host_srv_serror_rate',
                        'num_root','num_outbound_cmds','srv_rerror_rate','srv_serror_rate'], axis=1, inplace=True)

### Variable reduction using Select K-Best technique

In [30]:
X = train_new[train_new.columns.difference(['attack_class'])]
X_new = SelectKBest(f_classif, k=15).fit(X, train_new['attack_class'] )

In [31]:
X_new.get_support()

array([False, False, False, False, False, False, False, False,  True,
       False,  True, False, False, False, False, False,  True, False,
       False, False, False, False,  True, False, False, False,  True,
        True,  True,  True, False, False, False, False, False, False,
        True, False, False, False,  True, False, False,  True,  True,
       False, False, False, False,  True,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [33]:
# capturing the important variables
KBest_features=X.columns[X_new.get_support()]
KBest_features

Index(['attack_neptune', 'attack_normal', 'attack_satan', 'count',
       'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
       'dst_host_same_srv_rate', 'dst_host_srv_count', 'flag_S0', 'flag_SF',
       'last_flag', 'logged_in', 'same_srv_rate', 'serror_rate',
       'service_http'],
      dtype='object')

Variables selected for the model building using Select KBest -:

attack_neptune , attack_normal , attack_satan , count , dst_host_diff_srv_rate , dst_host_same_src_port_rate , dst_host_same_srv_rate , dst_host_srv_count , flag_S0 , flag_SF , last_flag , logged_in , same_srv_rate , serror_rate , service_http

In [34]:
train=train_new
test=test_new

## Create model and Evaluate

In [37]:
top_features=['attack_neptune','attack_normal','attack_satan','count','dst_host_diff_srv_rate','dst_host_same_src_port_rate','dst_host_same_srv_rate','dst_host_srv_count','flag_S0','flag_SF','last_flag','logged_in','same_srv_rate','serror_rate','service_http']
X_train = train[top_features]
y_train = train['attack_class']
X_test = test[top_features]
y_test = test['attack_class']

### KNN (K Nearest Neighbour 

In [38]:
k_neigh = KNeighborsClassifier(n_neighbors=3)
k_neigh.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [39]:
y_pred=k_neigh.predict(X_test)

In [45]:
print(accuracy_score(y_test, y_pred))

0.753981280220024


In [46]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.84      0.94      0.88      9711
         1.0       0.84      0.83      0.83      7459
         2.0       0.40      0.70      0.51      2421
         3.0       0.00      0.00      0.00      2885
         4.0       0.00      0.00      0.00        67

    accuracy                           0.75     22543
   macro avg       0.41      0.49      0.45     22543
weighted avg       0.68      0.75      0.71     22543



In [47]:
print(confusion_matrix(y_test,y_pred))

[[9122  461  128    0    0]
 [ 818 6182  459    0    0]
 [ 504  224 1693    0    0]
 [ 463  516 1906    0    0]
 [   1    1   65    0    0]]


### Naive Bayes

In [49]:
gnb_clf = GaussianNB()
gnb_clf.fit(X_train, y_train)

GaussianNB()

In [50]:
y_pred=gnb_clf.predict(X_test)

In [51]:
print(accuracy_score(y_test, y_pred))

0.7916869981812537


In [52]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      9711
         1.0       0.97      0.79      0.87      7459
         2.0       0.33      0.93      0.49      2421
         3.0       0.00      0.00      0.00      2885
         4.0       0.00      0.00      0.00        67

    accuracy                           0.79     22543
   macro avg       0.46      0.54      0.47     22543
weighted avg       0.79      0.79      0.77     22543



In [53]:
print(confusion_matrix(y_test,y_pred))

[[9711    0    0    0    0]
 [   0 5883 1576    0    0]
 [   0  168 2253    0    0]
 [   0    3 2882    0    0]
 [   0    0   67    0    0]]


### Decision Tree

#### Fine tune Hyperparameters

In [54]:
param_grid = {'max_depth': np.arange(3, 9),
             'max_features': np.arange(3,9)}

In [57]:
tree = GridSearchCV(DecisionTreeClassifier(), param_grid, cv = 5)
tree.fit( X_train, y_train )

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': array([3, 4, 5, 6, 7, 8]),
                         'max_features': array([3, 4, 5, 6, 7, 8])})

In [58]:
tree.best_params_

{'max_depth': 8, 'max_features': 8}

#### build decision tree model

In [59]:
clf_tree = DecisionTreeClassifier( max_depth = 8, max_features=8 )
clf_tree.fit( X_train, y_train )

DecisionTreeClassifier(max_depth=8, max_features=8)

In [60]:
y_pred=clf_tree.predict(X_test)

In [61]:
print(accuracy_score(y_test, y_pred))

0.8055272146564344


In [62]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      9711
         1.0       0.96      0.83      0.89      7459
         2.0       0.35      0.93      0.51      2421
         3.0       0.00      0.00      0.00      2885
         4.0       0.00      0.00      0.00        67

    accuracy                           0.81     22543
   macro avg       0.46      0.55      0.48     22543
weighted avg       0.79      0.81      0.78     22543



In [63]:
print(confusion_matrix(y_test,y_pred))

[[9711    0    0    0    0]
 [   0 6206 1253    0    0]
 [   0  179 2242    0    0]
 [   0  103 2782    0    0]
 [   0    0   67    0    0]]


## Observations

- Considering higher accuracy and minor differences in prediction capabilities Decision Tree Classifier can be finalized.